// <auto-generated />
namespace Capston_Clean_Slate2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class thisone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thisone));
        
        string IMigrationMetadata.Id
        {
            get { return "201810091723562_thisone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
